<?php

namespace ElasticExportBasicPriceSearchEngine\Catalog\DataProviders;

/**
 * Class BaseFieldsDataProvider
 *
 * @package ElasticExportBasicPriceSearchEngine\Catalog\DataProviders
 */
class BaseFieldsDataProvider
{
    /**
     * @return array
     */
    public function get():array
    {
        return [
//            [
//                'key' => 'name.de',
//                'simplifiedKey' => 'name.de',
//                'required' => true,
//                'label' => 'Name',
//                'default' => 'item-id',
//                'type' => 'string',
//            	'isMapping' => false,
//            ],
            [
                'key' => 'name.de',
                'label' => 'Name',
                'required' => true,
                'default' => 'variation-name',
                'type' => 'variation',
                'fieldKey' => 'name',
                'isMapping' => false,
            ],
            [
                'key' => 'article_id',
                'label' => 'Article Id',
                'required' => false,
                'default' => 'item-id',
                'type' => 'item',
                'fieldKey' => 'id',
                'isMapping' => false,
            ],
            [
                'key' => 'deeplink',
                'label' => 'Deeplink',
                'required' => false,
                'default' => '',
                'type' => 'text',
                'fieldKey' => '',
                'isMapping' => false,
            ],
            [
                'key' => 'short_description',
                'label' => 'Short description',
                'required' => false,
                'default' => 'itemText-shortDescription',
                'type' => 'text',
                'fieldKey' => 'shortDescription',
                'isMapping' => false,
            ],
            [
                'key' => 'description',
                'label' => 'Description',
                'required' => false,
                'default' => 'itemText-description',
                'type' => 'text',
                'fieldKey' => 'description',
                'isMapping' => false,
            ],
            [
                'key' => 'article',
                'label' => 'Article No',
                'required' => false,
                'default' => 'variation-number',
                'type' => 'number',
                'fieldKey' => 'number',
                'isMapping' => false,
            ],
            [
                'key' => 'producer',
                'label' => 'Producer',
                'required' => false,
                'default' => 'item-manufacturerId',
                'type' => 'item',
                'fieldKey' => 'manufacturer.id',
                'isMapping' => false,
            ],
            [
                'key' => 'model',
                'label' => 'Model',
                'required' => false,
                'default' => 'variation-model',
                'type' => 'variation',
                'fieldKey' => 'model',
                'isMapping' => false,
            ],
            [
                'key' => 'availability',
                'label' => 'Availability',
                'required' => false,
                'default' => 'variation-availability',
                'type' => 'variation',
                'fieldKey' => 'availability',
                'isMapping' => false,
            ],
            [
                'key' => 'ean',
                'label' => 'EAN',
                'required' => false,
                'default' => 'barcode-1',
                'type' => 'barcode-code',
                'fieldKey' => 'code',
                'isMapping' => false,
            ],
            [
                'key' => 'isbn',
                'label' => 'ISBN',
                'required' => false,
                'default' => 'barcode-4',
                'type' => 'barcode-code',
                'fieldKey' => 'code',
                'isMapping' => false,
            ],
            [
                'key' => 'unit',
                'label' => 'Unit',
                'required' => false,
                'default' => 'item-id',
                'type' => 'string',
                'fieldKey' => '',
                'isMapping' => false,
            ],
            [
                'key' => 'price',
                'label' => 'Price',
                'required' => false,
                'default' => 'salesPrice-1',
                'type' => 'price',
                'fieldKey' => 'price',
                'isMapping' => false,
            ],
            [
                'key' => 'price_old',
                'label' => 'Price old',
                'required' => false,
                'default' => 'item-id',
                'type' => 'string',
                'fieldKey' => '',
                'isMapping' => false,
            ],
            [
                'key' => 'weight',
                'label' => 'Weight',
                'required' => false,
                'default' => 'variation-weightNetG',
                'type' => 'variation',
                'fieldKey' => 'weightNetG',
                'isMapping' => false,
            ],
            [
                'key' => 'category1',
                'label' => 'Category1',
                'required' => false,
                'default' => 'defaultCategory-id',
                'type' => 'default-category',
                'fieldKey' => 'categoryId',
                'isMapping' => false,
            ],
            [
                'key' => 'category2',
                'label' => 'Category2',
                'required' => false,
                'default' => '',
                'type' => 'string',
                'fieldKey' => '',
                'isMapping' => false,
            ],
            [
                'key' => 'category3',
                'label' => 'Category3',
                'required' => false,
                'default' => '',
                'type' => 'string',
                'fieldKey' => '',
                'isMapping' => false,
            ],
            [
                'key' => 'category4',
                'label' => 'Category4',
                'required' => false,
                'default' => '',
                'type' => 'string',
                'fieldKey' => '',
                'isMapping' => false,
            ],
            [
                'key' => 'category5',
                'label' => 'Category5',
                'required' => false,
                'default' => '',
                'type' => 'string',
                'fieldKey' => '',
                'isMapping' => false,
            ],
            [
                'key' => 'category6',
                'label' => 'Category6',
                'required' => false,
                'default' => '',
                'type' => 'string',
                'fieldKey' => '',
                'isMapping' => false,
            ],
            [
                'key' => 'category_concat',
                'label' => 'Category Concat',
                'required' => false,
                'default' => '',
                'type' => 'string',
                'fieldKey' => '',
                'isMapping' => false,
            ],
            [
                'key' => 'image_url_preview',
                'label' => 'Image Url Preview',
                'required' => false,
                'default' => '',
                'type' => 'string',
                'fieldKey' => '',
                'isMapping' => false,
            ],
            [
                'key' => 'image_url',
                'label' => 'Image Url',
                'required' => false,
                'default' => '',
                'type' => 'string',
                'fieldKey' => '',
                'isMapping' => false,
            ],
            [
                'key' => 'shipment_and_handling',
                'label' => 'Shipment & Handling',
                'required' => false,
                'default' => '',
                'type' => 'string',
                'fieldKey' => '',
                'isMapping' => false,
            ],
            [
                'key' => 'unit_price',
                'label' => 'Unit Price',
                'required' => false,
                'default' => '',
                'type' => 'string',
                'fieldKey' => '',
                'isMapping' => false,
            ],
            [
                'key' => 'unit_price_value',
                'label' => 'Unit Price Value',
                'required' => false,
                'default' => '',
                'type' => 'string',
                'fieldKey' => '',
                'isMapping' => false,
            ],
            [
                'key' => 'unit_price_lot',
                'label' => 'Unit Price Lot',
                'required' => false,
                'default' => '',
                'type' => 'string',
                'fieldKey' => '',
                'isMapping' => false,
            ],
            [
                'key' => 'variation_id',
                'label' => 'Variation Id',
                'required' => false,
                'default' => 'variation-id',
                'type' => 'variation',
                'fieldKey' => 'id',
                'isMapping' => false,
            ]
        ];
    }
}
